apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-server
spec:
  replicas: 3
  selector:
    matchLabels:
      type: front-end
  template:
    metadata:
      name: nginx-server
      labels:
        type: front-end
    spec:
      containers:
      - name: nginx
        image: nginx