pipeline {

  agent any 

  stages {
    stage('Clone Repository'){
      steps {
        git url:'https://github.com/omkarsathe01/bb-devops-assignment', branch:'main'
        sh 'ls -ltra'
      }
    }

    stage('Create Deployments'){
      steps {
        sh '''
        chmod 777 deployments-script.sh
        ./deployments-script.sh
        '''
      }
    }

    stage('Create Services'){
      steps {
        sh '''
        chmod 777 services-script.sh
        ./services-script.sh
        '''
      }
    }
  }
}