apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: vote
  labels:
    name: redis
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-deployment-pod
      app: demo-voting-app
  template:
    metadata:
      name: redis-deployment-pod
      labels:
        name: redis-deployment-pod
        app: demo-voting-app
    spec:
      containers:
      - name: redis-deployment
        image: redis:alpine
        volumeMounts:
        - mountPath: /data
          name: redis-data
      volumes:
      - name: redis-data
        emptyDir: {}