apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result
  namespace: vote
spec:
  selector:
    name: result-deployment-pod
    app: demo-voting-app
  type: NodePort
  ports:
  - port: 5001
    targetPort: 80
    nodePort: 31001